
OHLCV_TIMESTAMP = 0
OHLCV_OPEN = 1
OHLCV_HIGH = 2
OHLCV_LOW = 3
OHLCV_CLOSE = 4
OHLCV_VOLUME = 5

SIGNAL_NONE = 0
SIGNAL_BUY = 1
SIGNAL_SELL = 2
SIGNAL_HOLD = 3

MODE_DRY = 0
MODE_RUN = 1
MODE_BOT = 2
MODE_SIM = 3

SETTING_INI_PATH = 'setting.ini'
WALLET_INI_PATH = 'wallet.ini'
STRATEGY_INI_PATH = 'strategy.ini'
SIGNAL_INI_PATH = 'signal.ini'
RANK_INI_PATH = 'rank.ini'

